=== ivanagui2/minuteproject-code/trunk/minuteKernel/config/mp-config.xsd
<xs:schema id="generator-config" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://minuteproject.sf.net/xsd/mp-config" targetNamespace="http://minuteproject.sf.net/xsd/mp-config">

    <xs:complexType name="condition">
        <xs:attribute name="type" type="xs:string" />
        <xs:attribute name="startsWith" type="xs:string" />
        <xs:attribute name="result" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="property">
        <xs:sequence>
            <xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" ></xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
        <xs:attribute name="tag" type="xs:string" />
        <xs:attribute name="alias" type="xs:string" />
    </xs:complexType>
    
    <xs:complexType name="driver">
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="version" type="xs:string" />
        <xs:attribute name="groupId" type="xs:string" />
        <xs:attribute name="artifactId" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="dataSource">
        <xs:sequence>
            <xs:element name="driverClassName" type="xs:string"
                minOccurs="0" />
            <xs:element name="url" type="xs:string" minOccurs="0" />
            <xs:element name="username" type="xs:string" minOccurs="0" />
            <xs:element name="password" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="primaryKeyPolicy">
        <xs:sequence>
            <xs:element name="primaryKeyPolicyPattern" minOccurs="0"
                maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="name" type="xs:string" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="oneGlobal" type="xs:string" />
    </xs:complexType>

    <xs:element name="generator-config" type="generator-config">
        <xs:annotation>
            <xs:documentation source="version">3.0.0+</xs:documentation>
            <xs:documentation source="description">
                The
                <code>&lt;project&gt;</code>
                element is the root of the descriptor.
                The following table lists all
                of the possible child elements.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:complexType name="generator-config">
        <xs:sequence>
            <xs:element name="condition" type="condition" />
            <xs:element name="property" type="property" />
            <xs:element name="configuration" type="configuration"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="generation-condition">
        <xs:sequence>
            <xs:element name="condition" type="condition" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="business-package">
        <xs:sequence>
            <xs:element name="condition" type="condition" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="default" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="column-naming-convention">
        <xs:attribute name="type" type="xs:string" />
        <xs:attribute name="pattern-to-strip" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="reference-naming-convention">
        <xs:attribute name="type" type="xs:string" />
        <xs:attribute name="is-to-plurialize" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="conventions">
        <xs:sequence>
            <xs:element name="column-naming-convention" type="column-naming-convention"
                minOccurs="0" maxOccurs="unbounded">
            </xs:element>
            <xs:element name="reference-naming-convention" type="reference-naming-convention"
                minOccurs="0" maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="package">
        <xs:sequence>
            <xs:element name="security-color" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="roles" type="xs:string" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="alias" type="xs:string" />
    </xs:complexType>


    <xs:complexType name="virtual-primary-key">
        <xs:sequence>
            <xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="isRealPrimaryKey" type="xs:string" />
    </xs:complexType>


    <xs:complexType name="semantic-reference">
        <xs:sequence>
            <xs:element name="sql-path" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="path" type="xs:string" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="field">
        <xs:sequence>
            <xs:element name="stereotype" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="stereotype" type="xs:string" />
                </xs:complexType>
            </xs:element>
            <xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="linkToTargetEntity" type="xs:string" />
        <xs:attribute name="linkToTargetField" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="entity">
        <xs:sequence>
            <xs:element name="virtual-primary-key" type="virtual-primary-key"
                minOccurs="0" maxOccurs="unbounded">
            </xs:element>
            <xs:element name="semantic-reference" type="semantic-reference"
                minOccurs="0" maxOccurs="unbounded">
            </xs:element>
            <xs:element name="field" minOccurs="0" type="field"
                maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="content-type" type="xs:string" />
        <xs:attribute name="alias" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="enrichment">
        <xs:sequence>
            <xs:element name="conventions" type="conventions"
                minOccurs="0" maxOccurs="unbounded">
            </xs:element>
            <xs:element name="package" type="package" minOccurs="0"
                maxOccurs="unbounded">
            </xs:element>
            <xs:element name="entity" type="entity" minOccurs="0"
                maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="function-model">
        <xs:sequence>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="business-model">
        <xs:sequence>
            <xs:element name="generation-condition" type="generation-condition"
                minOccurs="0" maxOccurs="unbounded">
            </xs:element>
            <xs:element name="business-package" type="business-package"
                minOccurs="0" maxOccurs="unbounded">
            </xs:element>
            <xs:element name="enrichment" type="enrichment" minOccurs="0"
                maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="model">
        <xs:sequence>
            <xs:element name="data-model" type="data-model" minOccurs="0"
                maxOccurs="unbounded">
            </xs:element>
            <xs:element name="business-model" type="business-model"
                minOccurs="0" maxOccurs="unbounded">
            </xs:element>
            <xs:element name="function-model" type="function-model"
                minOccurs="0" maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="version" type="xs:string" />
        <xs:attribute name="package-root" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="targets">
        <xs:sequence>
            <xs:element name="target" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
                    </xs:sequence>
                    <xs:attribute name="refname" type="xs:string" />
                    <xs:attribute name="name" type="xs:string" />
                    <xs:attribute name="fileName" type="xs:string" />
                    <xs:attribute name="outputdir-root" type="xs:string" />
                    <xs:attribute name="templatedir-root" type="xs:string" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="configuration">
        <xs:sequence>
            <xs:element name="model" type="model" minOccurs="0"
                maxOccurs="unbounded">
            </xs:element>
            <xs:element name="targets" type="targets" minOccurs="0"
                maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="data-model">
        <xs:sequence>
            <xs:element type="driver" name="driver" minOccurs="0" maxOccurs="unbounded">
            </xs:element>
            <xs:element type="dataSource" name="dataSource" minOccurs="0" maxOccurs="unbounded">
            </xs:element>
            <xs:element name="primaryKeyPolicy" type="primaryKeyPolicy">
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== ivanagui2/minuteproject-code/trunk/minuteDemo/demo/config/mp-config-Liferay.xml
<!DOCTYPE root>
<generator-config xmlns="http://minuteproject.sf.net/xsd/mp-config" 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:noNamespaceSchemaLocation="mp-config.xsd">
    <configuration>
		<model name="petshop" version="1.0" package-root="net.sf.mp.demo.jpa2">
			<data-model>
			    <driver name="hsqldb" version="1.8.0.7" groupId="hsqldb" artifactId="hsqldb"></driver>
			    <dataSource>	
					<driverClassName>org.hsqldb.jdbcDriver</driverClassName>
					<url>jdbc:hsqldb:file:../../sample/hsql/petshop</url>
					<username>sa</username>
					<password></password>	
				</dataSource>
				<!-- for Oracle and DB2 please set the schema 
				<schema> </schema>
				 -->
				<primaryKeyPolicy oneGlobal="true" oneForEachTable="false">
					<primaryKeyPolicyPattern name="sequencePattern" sequenceName="hibernate_sequence"></primaryKeyPolicyPattern>
				</primaryKeyPolicy> 
			</data-model>
			<business-model>
 				<generation-condition>
					<condition type="exclude" startsWith="DUAL"></condition>
 					<condition type="exclude" endsWith="_GEN"></condition>
				</generation-condition> 	
				<business-package default="pet">
					<condition type="package" startsWith="PRODUCT" result="product"></condition>
					<condition type="package" startsWith="ITEM" result="product"></condition>
				</business-package>	
				<enrichment>
				   <conventions>
				      <entity-naming-convention type="apply-strip-table-name-prefix" pattern-to-strip="SYS,FIN"/>
				      <column-naming-convention type="apply-fix-primary-key-column-name-when-no-ambiguity" default-value="ID"/>
				      <reference-naming-convention type="apply-referenced-alias-when-no-ambiguity" is-to-plurialize="true"></reference-naming-convention>
				   </conventions>
				    <package name="product">
				    	<entity-group entities="PRODUCT"></entity-group>
				    	<entity-group entities="ITEM"></entity-group>
				    </package>
					<entity name="PRODUCT" alias="MY_GOOD_PRODUCT">				
					</entity>				    
					<entity name="ITEM" alias="MY_GOOD_ITEM" comment="my item table">
						<field name="PRODUCTID" alias="THIS_IS_MY_PRODUCT" comment="my product field reference"></field>					
					</entity>				    
					<entity name="CATEGORY" content-type="reference-data" >
					   <semantic-reference>
					     <sql-path path="NAME"/>
					   </semantic-reference>					
					</entity>
				</enrichment>					
			</business-model>
		</model>	
 		<targets catalog-entry="Liferay">	
		</targets>
	</configuration>
</generator-config>
