=== ivanagui2/minuteproject-code/minuteKernel/config/mp-config.xsd
<xs:schema id="generator-config" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://minuteproject.sf.net/xsd/mp-config">
  <xs:element name="condition">
    <xs:complexType>
      <xs:attribute name="type" type="xs:string" />
      <xs:attribute name="startsWith" type="xs:string" />
      <xs:attribute name="result" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="property">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" />
      <xs:attribute name="value" type="xs:string" />
      <xs:attribute name="tag" type="xs:string" />
      <xs:attribute name="alias" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="driver" >
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" />
      <xs:attribute name="version" type="xs:string" />
      <xs:attribute name="groupId" type="xs:string" />
      <xs:attribute name="artifactId" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="generator-config">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="condition" />
        <xs:element ref="property" />
        <xs:element name="configuration">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="model" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="data-model" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="driver" minOccurs="0" maxOccurs="unbounded">
                          </xs:element>
                          <xs:element name="dataSource" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="driverClassName" type="xs:string" minOccurs="0" />
                                <xs:element name="url" type="xs:string" minOccurs="0" />
                                <xs:element name="username" type="xs:string" minOccurs="0" />
                                <xs:element name="password" type="xs:string" minOccurs="0" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="primaryKeyPolicy" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="primaryKeyPolicyPattern" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:attribute name="name" type="xs:string" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="oneGlobal" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="business-model" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="generation-condition" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element ref="condition" minOccurs="0" maxOccurs="unbounded" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="business-package" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element ref="condition" minOccurs="0" maxOccurs="unbounded" />
                              </xs:sequence>
                              <xs:attribute name="default" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="enrichment" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="conventions" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="column-naming-convention" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:attribute name="type" type="xs:string" />
                                          <xs:attribute name="pattern-to-strip" type="xs:string" />
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="reference-naming-convention" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:attribute name="type" type="xs:string" />
                                          <xs:attribute name="is-to-plurialize" type="xs:string" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="package" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="security-color" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:attribute name="roles" type="xs:string" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" />
                                    <xs:attribute name="alias" type="xs:string" />
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="entity" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="virtual-primary-key" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
                                          </xs:sequence>
                                          <xs:attribute name="isRealPrimaryKey" type="xs:string" />
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="semantic-reference" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="sql-path" minOccurs="0" maxOccurs="unbounded">
                                              <xs:complexType>
                                                <xs:attribute name="path" type="xs:string" />
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="field" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="stereotype" minOccurs="0" maxOccurs="unbounded">
                                              <xs:complexType>
                                                <xs:attribute name="stereotype" type="xs:string" />
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
                                          </xs:sequence>
                                          <xs:attribute name="name" type="xs:string" />
                                          <xs:attribute name="linkToTargetEntity" type="xs:string" />
                                          <xs:attribute name="linkToTargetField" type="xs:string" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" />
                                    <xs:attribute name="content-type" type="xs:string" />
                                    <xs:attribute name="alias" type="xs:string" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" />
                  <xs:attribute name="version" type="xs:string" />
                  <xs:attribute name="package-root" type="xs:string" />
                </xs:complexType>
              </xs:element>
              <xs:element name="targets" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="target" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                        <xs:attribute name="refname" type="xs:string" />
                        <xs:attribute name="name" type="xs:string" />
                        <xs:attribute name="fileName" type="xs:string" />
                        <xs:attribute name="outputdir-root" type="xs:string" />
                        <xs:attribute name="templatedir-root" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ivanagui2/minuteproject-code/minuteFitNesse/config/mp-config-TRANXY-JPA2.xml
<!DOCTYPE root>
<generator-config xmlns="http://minuteproject.sf.net/xsd/mp-config" 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:noNamespaceSchemaLocation="../config/mp-config.xsd">
    <configuration>
        <conventions>
            <target-convention type="enable-updatable-code-feature" />
        </conventions>
        <model name="tranxy" version="1.0" package-root="net.sf.mp.demo">
            <data-model>
                <driver name="mysql" version="5.1.16" groupId="mysql"
                    artifactId="mysql-connector-java"></driver>
                <dataSource>
                    <driverClassName>org.gjt.mm.mysql.Driver</driverClassName>
                    <url>jdbc:mysql://127.0.0.1:3306/tranxy</url>
                    <username>root</username>
                    <password>mysql</password>
                </dataSource>
                <primaryKeyPolicy oneGlobal="false" >
                    <primaryKeyPolicyPattern name="autoincrementPattern"></primaryKeyPolicyPattern>
                </primaryKeyPolicy>
            </data-model>
            <business-model>
                <business-package default="tranxy">
                    <condition type="package" startsWith="trans" result="translation"></condition>
                </business-package>
                <enrichment>
                    <conventions>
                        <!-- manipulate the structure and entities BEFORE manipulating the 
                            entities -->
                        <column-naming-convention type="apply-strip-column-name-suffix"
                            pattern-to-strip="ID" />
                        <reference-naming-convention
                            type="apply-referenced-alias-when-no-ambiguity" is-to-plurialize="true" />
                         <reference-naming-convention type="apply-many-to-many-aliasing" is-to-plurialize="true"/>
                    </conventions>
                    <entity name="language_x_translator">
                        <field name="language_id" linkReferenceAlias="translating_language" linkToTargetEntity="LANGUAGE"/>
                        <field name="user_id" linkReferenceAlias="translator" linkToTargetEntity="USER"/>
                    </entity>
                    <entity name="LANGUAGE_X_SPEAKER">
                        <field name="LANGUAGE_ID" linkToTargetEntity="LANGUAGE"
                            linkToTargetField="IDLANGUAGE" linkReferenceAlias="spoken_language" />
                        <field name="user_id" linkReferenceAlias="speaker" linkToTargetEntity="USER"/>
                    </entity>
                    <entity name="APPLICATION">
                        <field name="TYPE">
                            <property tag="checkconstraint" alias="application_type">
                                <property name="OPENSOURCE"/>
                                <property name="COPYRIGHT" />
                            </property>
                        </field>
                    </entity>
                </enrichment>
            </business-model>
        </model>
        <targets>
            <target refname="JPA2" fileName="mp-template-config-JPA2.xml"
                outputdir-root="../../dev/latvianjug/output/JPA2" templatedir-root="../../minuteTemplate/template/framework/jpa">
                <property name="add-querydsl" value="2.1.2"></property>
                <property name="add-jpa2-implementation" value="hibernate"></property>
            </target>
            
            <target refname="CACHE-LIB" fileName="mp-template-config-CACHE-LIB.xml"
                templatedir-root="../../minuteTemplate/template/framework/cache">
            </target>
            
            <target refname="LIB" fileName="mp-template-config-bsla-LIB-features.xml"
                templatedir-root="../../minuteTemplate/template/framework/bsla">
            </target>

        </targets>
    </configuration>
</generator-config>

=== ivanagui2/minuteproject-code/minuteKernel/config-demo/mp-config-sample-tranxy-application-2-model.xml
<?xml version="1.0" encoding="utf-8"?>
<generator-config noNamespaceSchemaLocation="../config/mp-config.xsd">
	<configuration>
		<conventions>
			<target-convention type="enable-updatable-code-feature" />
		</conventions>
		<application name="appli" version="1.0" package-root="net.sf.mp.demo">
			<models>
				<model name="tranxy">
					<data-model>
						<driver name="mysql" version="5.1.16" groupId="mysql"
							artifactId="mysql-connector-java" />
						<dataSource>
							<driverClassName>org.gjt.mm.mysql.Driver</driverClassName>
							<url>jdbc:mysql://127.0.0.1:3306/tranxy</url>
							<username>root</username>
							<password>mysql</password>
						</dataSource>
						<primaryKeyPolicy oneGlobal="false">
							<primaryKeyPolicyPattern name="autoincrementPattern" />
						</primaryKeyPolicy>
					</data-model>
					<business-model>
						<business-package default="tranxy">
							<condition type="package" startsWith="trans" result="translation" />
						</business-package>
						<enrichment>
							<conventions>
								<!-- manipulate the structure and entities BEFORE manipulating the 
									entities -->
								<column-naming-convention type="apply-strip-column-name-suffix"
									pattern-to-strip="ID" />
								<reference-naming-convention
									type="apply-referenced-alias-when-no-ambiguity"
									is-to-plurialize="true" />
								<reference-naming-convention type="apply-many-to-many-aliasing"
									is-to-plurialize="true" />
							</conventions>
							<entity name="language_x_translator">
								<field name="language_id" linkReferenceAlias="translating_language"
									linkToTargetEntity="LANGUAGE" />
								<field name="user_id" linkReferenceAlias="translator"
									linkToTargetEntity="USER" />
							</entity>
							<entity name="request_key">
								<field name="language_id" linkReferenceAlias="language"
									linkToTargetEntity="LANGUAGE" />
								<field name="translation_request_id" linkReferenceAlias="translation_request"
									linkToTargetEntity="translation_request" />
							</entity>
							<entity name="LANGUAGE_X_SPEAKER">
								<field name="LANGUAGE_ID" linkToTargetEntity="LANGUAGE"
									linkToTargetField="IDLANGUAGE" linkReferenceAlias="spoken_language" />
								<field name="user_id" linkReferenceAlias="speaker"
									linkToTargetEntity="USER" />
							</entity>
							<entity name="APPLICATION">
								<field name="TYPE">
									<property tag="checkconstraint" alias="application_type">
										<property name="OPENSOURCE" />
										<property name="COPYRIGHT" />
									</property>
								</field>
							</entity>
						</enrichment>
					</business-model>
				</model>
				<model name="devops">
					<data-model>
						<driver name="mysql" version="5.1.16" groupId="mysql"
							artifactId="mysql-connector-java" />
						<dataSource>
							<driverClassName>org.gjt.mm.mysql.Driver</driverClassName>
							<url>jdbc:mysql://localhost:3306/mp_devops</url>
							<username>root</username>
							<password>mysql</password>
						</dataSource>
						<primaryKeyPolicy oneGlobal="false">
							<primaryKeyPolicyPattern name="autoincrementPattern" />
						</primaryKeyPolicy>
					</data-model>
					<business-model>
						<business-package default="devops">
							<condition type="package" startsWith="MP_I18N" result="i18n" />
							<condition type="package" startsWith="MP_RIGHT" result="right" />
						</business-package>
						<enrichment>
							<conventions>
								<table-default-primary-key-convention
									type="apply-default-primary-key-otherwise-first-one"
									default-primary-key-names="ID" />
								<view-primary-key-convention
									type="apply-default-primary-key-otherwise-first-one"
									default-primary-key-names="IDENTIFIER,ID" />
							</conventions>
						</enrichment>
					</business-model>
				</model>
			</models>
		</application>
		<targets
			catalog-entry="WS-JEE,REST-CXF-Spring,REST-JEE,REST-SpringMVC,Vaadin,Primefaces-Spring,OpenXava" />
	</configuration>
</generator-config>
