=== ivanagui2/minuteproject-code/minuteKernel/config/mp-config.xsd
<xs:schema id="generator-config" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://minuteproject.sf.net/xsd/mp-config">
  <xs:element name="condition">
    <xs:complexType>
      <xs:attribute name="type" type="xs:string" />
      <xs:attribute name="startsWith" type="xs:string" />
      <xs:attribute name="result" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="property">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" />
      <xs:attribute name="value" type="xs:string" />
      <xs:attribute name="tag" type="xs:string" />
      <xs:attribute name="alias" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="driver" >
    <xs:complexType>
      <xs:attribute name="name" type="xs:string" />
      <xs:attribute name="version" type="xs:string" />
      <xs:attribute name="groupId" type="xs:string" />
      <xs:attribute name="artifactId" type="xs:string" />
    </xs:complexType>
  </xs:element>
  <xs:element name="generator-config">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="condition" />
        <xs:element ref="property" />
        <xs:element name="configuration">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="model" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="data-model" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="driver" minOccurs="0" maxOccurs="unbounded">
                          </xs:element>
                          <xs:element name="dataSource" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="driverClassName" type="xs:string" minOccurs="0" />
                                <xs:element name="url" type="xs:string" minOccurs="0" />
                                <xs:element name="username" type="xs:string" minOccurs="0" />
                                <xs:element name="password" type="xs:string" minOccurs="0" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="primaryKeyPolicy" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="primaryKeyPolicyPattern" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:attribute name="name" type="xs:string" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="oneGlobal" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="business-model" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="generation-condition" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element ref="condition" minOccurs="0" maxOccurs="unbounded" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="business-package" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element ref="condition" minOccurs="0" maxOccurs="unbounded" />
                              </xs:sequence>
                              <xs:attribute name="default" type="xs:string" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="enrichment" minOccurs="0" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="conventions" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="column-naming-convention" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:attribute name="type" type="xs:string" />
                                          <xs:attribute name="pattern-to-strip" type="xs:string" />
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="reference-naming-convention" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:attribute name="type" type="xs:string" />
                                          <xs:attribute name="is-to-plurialize" type="xs:string" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="package" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="security-color" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:attribute name="roles" type="xs:string" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" />
                                    <xs:attribute name="alias" type="xs:string" />
                                  </xs:complexType>
                                </xs:element>
                                <xs:element name="entity" minOccurs="0" maxOccurs="unbounded">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="virtual-primary-key" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
                                          </xs:sequence>
                                          <xs:attribute name="isRealPrimaryKey" type="xs:string" />
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="semantic-reference" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="sql-path" minOccurs="0" maxOccurs="unbounded">
                                              <xs:complexType>
                                                <xs:attribute name="path" type="xs:string" />
                                              </xs:complexType>
                                            </xs:element>
                                          </xs:sequence>
                                        </xs:complexType>
                                      </xs:element>
                                      <xs:element name="field" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="stereotype" minOccurs="0" maxOccurs="unbounded">
                                              <xs:complexType>
                                                <xs:attribute name="stereotype" type="xs:string" />
                                              </xs:complexType>
                                            </xs:element>
                                            <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
                                          </xs:sequence>
                                          <xs:attribute name="name" type="xs:string" />
                                          <xs:attribute name="linkToTargetEntity" type="xs:string" />
                                          <xs:attribute name="linkToTargetField" type="xs:string" />
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" />
                                    <xs:attribute name="content-type" type="xs:string" />
                                    <xs:attribute name="alias" type="xs:string" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" />
                  <xs:attribute name="version" type="xs:string" />
                  <xs:attribute name="package-root" type="xs:string" />
                </xs:complexType>
              </xs:element>
              <xs:element name="targets" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="target" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element ref="property" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                        <xs:attribute name="refname" type="xs:string" />
                        <xs:attribute name="name" type="xs:string" />
                        <xs:attribute name="fileName" type="xs:string" />
                        <xs:attribute name="outputdir-root" type="xs:string" />
                        <xs:attribute name="templatedir-root" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ivanagui2/minuteproject-code/minuteKernel/config/mp-config-ADF-Faces-HRSystem.xml
<!DOCTYPE root>
<generator-config xmlns="http://minuteproject.sf.net/xsd/mp-config"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xs:noNamespaceSchemaLocation="../config/mp-config.xsd">
	<configuration>
	    
        <conventions>
            <target-convention type="enable-updatable-code-feature" />
        </conventions>	
		<model name="hrsystem" version="1.0" package-root="org.mp.demo">
			<data-model>
			    <driver name="oracle" version="10.0.2.0.0" groupId="com.oracle" artifactId="ojdbc14"></driver>
			    <fileSource name="hrsystem" dir="c:/MinuteProject/data">
			    </fileSource>
			    <dataSource>	
					<driverClassName>oracle.jdbc.OracleDriver</driverClassName>
					<url>jdbc:oracle:thin:@localhost:1521:hrsystem</url>
					<username>HR</username>
					<password>oracle</password>	
				</dataSource>
				<!-- for Oracle and DB2 please set the schema  -->
				<schema>HR</schema>
				<!-- 
			    <dataSource>	
					<driverClassName>oracle.jdbc.OracleDriver</driverClassName>
					<url>jdbc:oracle:thin:@localhost:1521:hrsystem</url>
					<username>HR</username>
					<password>oracle</password>	
				</dataSource>
				<schema>HR</schema>
						 -->												 
				<primaryKeyPolicy oneGlobal="true">
					<primaryKeyPolicyPattern name="uuid" ></primaryKeyPolicyPattern>
				</primaryKeyPolicy> 
			</data-model>
			<business-model>

				<generation-condition exclude-views="true" default-type="exclude">
					<condition type="include" startsWith="COUNTRIES" ></condition>
					<condition type="include" startsWith="DEPARTMENTS" ></condition>
					<condition type="include" startsWith="EMPLOYEES" ></condition>
					<condition type="include" startsWith="JOB_HISTORY" ></condition>
					<condition type="include" startsWith="JOBS" ></condition>
					<condition type="include" startsWith="LOCATIONS" ></condition>
					<condition type="include" startsWith="REGIONS" ></condition>
					<condition type="include" startsWith="PS_TXN" ></condition>
				</generation-condition>		
				
				<business-package default="hr">
					<condition type="package" startsWith="COUNTRIES" result="hr"></condition>
					<condition type="package" startsWith="DEPARTMENTS" result="hr"></condition>
					<condition type="package" startsWith="EMPLOYEES" result="hr"></condition>
					<condition type="package" startsWith="JOB_HISTORY" result="hr"></condition>
					<condition type="package" startsWith="JOBS" result="hr"></condition>
					<condition type="package" startsWith="LOCATIONS" result="hr"></condition>
					<condition type="package" startsWith="REGIONS" result="hr"></condition>
					<condition type="package" startsWith="PS_TXN" result="hr"></condition>
				</business-package>	
				
				<enrichment>
				   <conventions>
				      <primary-key-convention type="apply-primary-key-on-entity-with-two-columns-only-and-foreign-key-otherwise-specified" />
				      <primary-key-convention type="apply-default-primary-key-otherwise-first-one" />
				      <entity-content-type-convention type="apply-content-type-to-entity-starting-with" pattern="I18N_" content-type="reference-data"/>
				      <entity-content-type-convention type="apply-content-type-to-entity-ending-with" pattern="_TYPE,_STATE,_CODE" content-type="reference-data"/>
				      <entity-semantic-reference-convention  pattern="CODE,LANGUAGE_CODE" description="LABEL" content-type="reference-data"/>
				      <property-convention scope="field" pattern="CREATED_ON" tag="trigger-insert-with-current-date" type="start-with"/>
				      <property-convention scope="field" pattern="LAST_UPDATED_ON" tag="trigger-insert-update-with-current-date" type="start-with"/>
				      <reference-naming-convention type="apply-referenced-alias-when-no-ambiguity" is-to-plurialize="true"></reference-naming-convention>
				      <check-constraint-convention field-pattern ="active" field-pattern-type="equals" field-content-type="string">
				      		<property name="true" value="T"></property>
				      		<property name="false" value="F"></property>
				      </check-constraint-convention>
				      <sql-mapping-convention type="varchar2-used-instead-of-varchar"></sql-mapping-convention>
				   </conventions>
				</enrichment>					
			</business-model>

		</model>	
		
		<targets outputdir-root="c:/dev/ADF_MP_GENERATION/MP4HR" >
		<!-- 
 			<post-generation-action command="ADF-FACES/Nif2-delivery" is-absolute-path="false"/>
 			 -->
 			<target refname="ADF FACES" 
			   name="ADF FACES"
			   fileName="mp-template-config-ADF-Faces.xml" 
			   outputdir-root="ADF-FACES-MODEL"
			   templatedir-root="../../minuteTemplate/template/framework/adf"
			   templatedir-ref="../../minuteTemplate/template/framework/i18n">  	
			   <property name="WEBLOGIC_HOME" value="D:/SOFT/SERVER/ORACLE/WLS/10.3.5.0-jdev-11.1.1.6.0"></property>		   
			   <property name="WLS_HOME" value="D:/SOFT/SERVER/ORACLE/WLS/10.3.5.0-jdev-11.1.1.6.0/wlserver_10.3"></property>		   
			   <property name="JDEV_HOME" value="D:/SOFT/SERVER/ORACLE/WLS/10.3.5.0-jdev-11.1.1.6.0/jdeveloper"></property>		   
		   	   
			   <property name="wls-username" value="weblogic"></property>		   
			   <property name="wls-password" value="weblogic01"></property>		   
			   <property name="wls-hostname" value="localhost"></property>		   
			   <property name="wls-port" value="7201"></property>
			   <property name="wls-deploy-target" value="AdminServer,soa_server1"></property>	
			   
			   <property name="adf-faces-custom-framework-home" value="c:\DEV\JSF\ADF\ADF-fwk"/>
			   <property name="adf-faces-custom-framework-package-name" value="eu.adf.fwk"/>
			   
			   <property name="adf-faces-backend-binding" value="ws-sdo"/>
			   
			</target>  
			
 			<target refname="ADF FACES" 
			   name="ADF FACES"
			   fileName="mp-template-config-ADF-Faces.xml" 
			   outputdir-root="ADF-FACES"
			   templatedir-root="../../minuteTemplate/template/framework/adf"
			   templatedir-ref="../../minuteTemplate/template/framework/i18n">  	
			   <property name="WEBLOGIC_HOME" value="D:/SOFT/SERVER/ORACLE/WLS/10.3.5.0-jdev-11.1.1.6.0"></property>		   
			   <property name="WLS_HOME" value="D:/SOFT/SERVER/ORACLE/WLS/10.3.5.0-jdev-11.1.1.6.0/wlserver_10.3"></property>		   
			   <property name="JDEV_HOME" value="D:/SOFT/SERVER/ORACLE/WLS/10.3.5.0-jdev-11.1.1.6.0/jdeveloper"></property>		   
		   	   
			   <property name="wls-username" value="weblogic"></property>		   
			   <property name="wls-password" value="weblogic01"></property>		   
			   <property name="wls-hostname" value="localhost"></property>		   
			   <property name="wls-port" value="7201"></property>
			   <property name="wls-deploy-target" value="AdminServer"></property>	
			   
			   <property name="adf-faces-custom-framework-home" value="c:\DEV\JSF\ADF\ADF-fwk"/>
			   <property name="adf-faces-custom-framework-package-name" value="eu.adf.fwk"/>
			   
			   <property name="adf-faces-backend-binding" value="ws-sdo"/>
			   
			</target>  

			<target refname="SDO" 
			   name="SDO" 
			   outputdir-root="ADF-SDO"
			   fileName="mp-template-config-ADF-SDO.xml" 
			   templatedir-root="../../minuteTemplate/template/framework/adf">  	
			   <property name="WEBLOGIC_HOME" value="D:/SOFT/SERVER/ORACLE/WLS/10.3.5.0-jdev-11.1.1.6.0"></property>		   
			   <property name="WLS_HOME" value="D:/SOFT/SERVER/ORACLE/WLS/10.3.5.0-jdev-11.1.1.6.0/wlserver_10.3"></property>		   
			   <property name="JDEV_HOME" value="D:/SOFT/SERVER/ORACLE/WLS/10.3.5.0-jdev-11.1.1.6.0/jdeveloper"></property>	
		   	   
			   <property name="wls-username" value="weblogic"></property>		   
			   <property name="wls-password" value="weblogic01"></property>		   
			   <property name="wls-hostname" value="localhost"></property>		   
			   <property name="wls-port" value="7201"></property>
			   <property name="wls-deploy-target" value="AdminServer,soa_server1"></property>
			</target> 
 
			<target 
			   name="Selenium" 
			   outputdir-root="ADF-TEST"
			   fileName="mp-template-config-selenium.xml" 
			   templatedir-root="../../minuteTemplate/template/framework/selenium">  
			   <property name="target-techno" value="adf"></property>			   
			   <property name="target-techno-type" value="front-end"></property>	
			   <property name="wls-hostname" value="localhost"></property>		   
			   <property name="wls-port" value="7201"></property>
			</target>  
			
			<target refname="SQL" 
			   name="SQL" 
			   fileName="mp-template-config-sqlutils.xml" 
			   templatedir-root="../../minuteTemplate/template/utils/db">  			   
			</target> 

			<target refname="LIB" 
			   fileName="mp-template-config-bsla-LIB-features.xml" 
			   templatedir-root="../../minuteTemplate/template/framework/bsla">
			</target>
			<target refname="COMMON-LIB" 
			   fileName="mp-template-config-COMMON-LIB.xml" 
			   templatedir-root="../../minuteTemplate/template/framework/common">
			</target>
							
		</targets>
	</configuration>
</generator-config>

=== ivanagui2/minuteproject-code/minuteDemo/demo/config/mp-config-REST.xml
<!DOCTYPE root>
<generator-config xmlns="http://minuteproject.sf.net/xsd/mp-config"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xs:noNamespaceSchemaLocation="mp-config.xsd">
	<configuration>
		<conventions>
			<target-convention type="enable-updatable-code-feature" />
		</conventions>
		<model name="petshop" version="1.0" package-root="net.sf.mp.demo">

			<data-model>
				<driver groupId="org.apache.derby" artifactId="derby"
					version="10.8.1.2" />
				<fileSource name="petshop" dir="c:/MinuteProject/data">
				</fileSource>
				<!-- <dataSource> <driverClassName>org.apache.derby.jdbc.ClientDriver</driverClassName> 
					<url>jdbc:derby://localhost:1527/sample</url> <username>app</username> <password>app</password> 
					</dataSource> <schema>app</schema> -->
				<dataSource>
					<driverClassName>org.hsqldb.jdbcDriver</driverClassName>
					<url>jdbc:hsqldb:hsql://127.0.0.1:9001/petshop</url>
					<username>sa</username>
					<password></password>
				</dataSource>

				<primaryKeyPolicy oneGlobal="true">
					<primaryKeyPolicyPattern name="autoincrementPattern" />
				</primaryKeyPolicy>
			</data-model>
			<business-model>
				<generation-condition>
					<condition type="exclude" startsWith="DUAL"></condition>
					<condition type="exclude" startsWith="ID_GEN"></condition>
					<condition type="exclude" startsWith="SEQUENCE"></condition>
				</generation-condition>
				<business-package default="pet">
					<condition type="package" startsWith="PRODUCT" result="product"></condition>
					<condition type="package" startsWith="ITEM" result="product"></condition>
				</business-package>
				<enrichment>
					<conventions>
						<entity-naming-convention type="apply-strip-table-name-prefix"
							pattern-to-strip="SYS,FIN" />
						<reference-naming-convention
							type="apply-referenced-alias-when-no-ambiguity" is-to-plurialize="true"></reference-naming-convention>
					</conventions>
					<package name="product">
						<entity-group entities="PRODUCT"></entity-group>
						<entity-group entities="ITEM"></entity-group>
					</package>
					<entity name="TAG_ITEM" master-relationship-field="ITEMID" />
					<entity name="PRODUCT" alias="MY_GOOD_PRODUCT">
					</entity>
					<entity name="ITEM" alias="MY_GOOD_ITEM" comment="my item table">
						<field name="PRODUCTID" alias="THIS_IS_MY_PRODUCT" comment="my product field reference"></field>
					</entity>
					<entity name="CATEGORY" content-type="reference-data">
						<semantic-reference>
							<sql-path path="NAME" />
						</semantic-reference>
					</entity>
				</enrichment>
			</business-model>
		</model>
		<targets catalog-entry="REST-JEE">
<!-- 
			<target refname="JPA2" name="JPA2" fileName="catalog/mp-template-config-JPA2.xml"
				outputdir-root="../output/REST-JEE/petshop/JPA2" templatedir-root="../../template/framework/jpa">
				<property name="add-querydsl" value="2.1.2"></property>
				<property name="add-jpa2-implementation" value="eclipselink"></property>
				<property name="add-xmlbinding" value="true"></property>
				<property name="add-xml-format" value="lowercase-hyphen"></property>		< - - java-variable, uppercase-underscore, lowercase-hyphen, java-class - - >
			</target>

			<target name="REST" fileName="catalog/mp-template-config-REST.xml"
				outputdir-root="../output/REST-JEE/petshop/REST" templatedir-root="../../template/framework/rest"
				templatedir-ref="../../template/framework/ejb">
				<property name="add-rest-implementation-jersey-version"
					value="1.9-ea03"></property>
			</target>

			<target refname="LIB" fileName="catalog/mp-template-config-bsla-LIB-features.xml"
				templatedir-root="../../template/framework/bsla">
			</target>
			<target refname="CACHE-LIB" fileName="catalog/mp-template-config-CACHE-LIB.xml"
				templatedir-root="../../template/framework/cache">
			</target>
			<target refname="COMMON-LIB" fileName="catalog/mp-template-config-COMMON-LIB.xml"
				templatedir-root="../../template/framework/common">
			</target>
			<target refname="SPRING-LIB" fileName="catalog/mp-template-config-SPRING-LIB.xml"
				templatedir-root="../../template/framework/spring">
			</target>

			<target refname="MavenMaster" name="maven"
				fileName="catalog/mp-template-config-maven.xml" outputdir-root="../output/REST-JEE/petshop"
				templatedir-root="../../template/framework/maven">
			</target>

			<target refname="Documentation" fileName="catalog/mp-template-config-documentation.xml"
				outputdir-root="../output/REST-JEE/petshop" templatedir-root="../../template/template">
			</target>
 -->
		</targets>
	</configuration>
</generator-config>
