=== ivanagui2/minuteproject-code/minuteKernel/config/mp-template-config.xsd
<?xml version="1.0"?>
<xs:schema id="target-config" xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://minuteproject.sf.net/xsd/mp-template-config" targetNamespace="http://minuteproject.sf.net/xsd/mp-template-config">
<xs:element name="target">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="architecture-target" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" />
            <xs:attribute name="description" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="plugin" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="name" type="xs:string" />
            <xs:attribute name="className" type="xs:string" />
          </xs:complexType>
        </xs:element>
        <xs:element name="template-target" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="template" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="property" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="name" type="xs:string" />
                        <xs:attribute name="value" type="xs:string" />
                        <xs:attribute name="tag" type="xs:string" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" />
                  <xs:attribute name="templateFileName" type="xs:string" />
                  <xs:attribute name="subdir" type="xs:string" />
                  <xs:attribute name="outputsubdir" type="xs:string" />
                  <xs:attribute name="technicalPackage" type="xs:string" />
                  <xs:attribute name="add-model-name" type="xs:string" />
                  <xs:attribute name="add-model-dir-name" type="xs:string" />
                  <xs:attribute name="file-extension" type="xs:string" />
                  <xs:attribute name="file-prefix" type="xs:string" />
                  <xs:attribute name="file-suffix" type="xs:string" />
                  <xs:attribute name="entity-specific" type="xs:string" />
                  <xs:attribute name="package-specific" type="xs:string" />
                  <xs:attribute name="model-specific" type="xs:string" />
                  <xs:attribute name="check-template-to-generate" type="xs:string" />
                  <xs:attribute name="is-template-to-generate-method" type="xs:string" />
                  <xs:attribute name="field-specific" type="xs:string" />
                  <xs:attribute name="file-name-builder-plugin" type="xs:string" />
                  <xs:attribute name="file-name-builder-method" type="xs:string" />
                  <xs:attribute name="application-specific" type="xs:string" />
                  <xs:attribute name="package-root" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="libdir" type="xs:string" />
            <xs:attribute name="tool" type="xs:string" />
            <xs:attribute name="outputdir" type="xs:string" />
            <xs:attribute name="package-root" type="xs:string" />
            <xs:attribute name="belongToPackage" type="xs:string" />
            <xs:attribute name="templatedir" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" />
    </xs:complexType>
</xs:element>
  <xs:element name="target-config">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="target" />
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ivanagui2/minuteproject-code/trunk/minuteKernel/config/mp-template-config-ADF-SDO.xml
<target name="ABL framework"
xmlns="http://minuteproject.sf.net/xsd/mp-template-config" 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:schemaLocation="../config/mp-template-config.xsd">	
	<architecture-target name="ABL" description="Automated Business Logic architecture">
	</architecture-target>	

    <plugin name="adfUtils" className="net.sf.minuteProject.plugin.oracle.AdfUtils"></plugin>

	<template-target 
    	name="ABL"
		libdir="lib/ADF_LIB.vm"
		outputdir="ViewController/src">

		<!-- ABL beans -->	
		<template name="ADF.Model.AppModule" templateFileName="ADF.Model.AppModule.vm" 
			subdir="" outputsubdir="" technicalPackage="view"
			file-extension="xml" file-prefix="" file-suffix="AppModule" 
			has-updatable-nature="true"
			scope-specific-value="model"
			>			
		</template>	
		
		<template name="ADF.Model.Entity" templateFileName="ADF.Model.Entity.vm" 
			subdir="" outputsubdir="" technicalPackage="view"
			file-extension="xml" file-prefix="" file-suffix="" 
			has-updatable-nature="true" add-package-name-dir="false"
			scope-specific-value="entity"
			>			
		</template>	
		
		<template name="ADF.Model.View" templateFileName="ADF.Model.View.vm" 
			subdir="" outputsubdir="" technicalPackage="view"
			file-extension="xml" file-prefix="" file-suffix="View" 
			has-updatable-nature="true"
			scope-specific-value="entity"
			>			
		</template>	
		
		<template name="ADF.Model.FkAssoc" templateFileName="ADF.Model.FkAssoc.vm" 
			subdir="" outputsubdir="" technicalPackage="view"
			file-extension="xml" file-prefix="" file-suffix="FkAssoc" 
			has-updatable-nature="true"
			scope-specific-value="reference"
			>			
		</template>	
		
		<template name="ADF.Model.FkLink" templateFileName="ADF.Model.FkLink.vm" 
			subdir="" outputsubdir="" technicalPackage="view"
			file-extension="xml" file-prefix="" file-suffix="FkLink" 
			has-updatable-nature="true"
			scope-specific-value="reference"
			>			
		</template>	
		
		<template name="ADF.Model.ViewController" templateFileName="ADF.Model.ViewController.vm" 
			subdir="" outputsubdir="" technicalPackage="view"
			file-extension="jpx" file-prefix="" file-suffix="ViewController" 
			has-updatable-nature="true"
			scope-specific-value="model"
			>			
		</template>	
		
		<template name="ADF.SDO.AppModuleServiceImplJava" templateFileName="ADF.SDO.AppModuleServiceImplJava.vm" 
			subdir="" outputsubdir="" technicalPackage="view.serviceinterface"
			file-extension="java" file-prefix="" file-suffix="AppModuleServiceImpl" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="model"
			>			
		</template>			
		
		<template name="ADF.SDO.AppModuleServiceJava" templateFileName="ADF.SDO.AppModuleServiceJava.vm" 
			subdir="" outputsubdir="" technicalPackage="view.serviceinterface"
			file-extension="java" file-prefix="" file-suffix="AppModuleService" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="model"
			>			
		</template>	
		
		<template name="ADF.SDO.AppModuleServiceWsdl" templateFileName="ADF.SDO.AppModuleServiceWsdl.vm" 
			subdir="" outputsubdir="" technicalPackage="view.serviceinterface"
			file-extension="wsdl" file-prefix="" file-suffix="AppModuleService" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="model"
			>			
		</template>	
		
		<template name="ADF.SDO.AppModuleServiceXsd" templateFileName="ADF.SDO.AppModuleServiceXsd.vm" 
			subdir="" outputsubdir="" technicalPackage="view.serviceinterface"
			file-extension="xsd" file-prefix="" file-suffix="AppModuleService" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="model"
			>			
		</template>	
		
		<template name="ADF.SDO.ejb-jar" templateFileName="ADF.SDO.ejb-jar.vm" 
			subdir="" outputsubdir="META-INF" technicalPackage=""
			file-extension="xml" file-prefix="" file-suffix="ejb-jar" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="application"
			>
		</template>	
		
		<template name="ADF.SDO.weblogic-ejb-jar" templateFileName="ADF.SDO.weblogic-ejb-jar.vm" 
			subdir="" outputsubdir="META-INF" technicalPackage=""
			file-extension="xml" file-prefix="" file-suffix="weblogic-ejb-jar" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="application"
			>			
		</template>	
		
    </template-target>


</target>

=== ivanagui2/minuteproject-code/minuteKernel/config/mp-template-config-ADF-SDO.xml
<target name="ABL framework"
xmlns="http://minuteproject.sf.net/xsd/mp-template-config" 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:schemaLocation="../config/mp-template-config.xsd">	
	<architecture-target name="ABL" description="Automated Business Logic architecture">
	</architecture-target>	

    <plugin name="adfUtils" className="net.sf.minuteProject.plugin.oracle.AdfUtils"></plugin>

	<template-target 
    	name="ADF Model src"
		libdir="lib/ADF_LIB.vm"
		outputdir="Model/src">

		<!-- ABL beans -->	
		<template name="ADF.Model.AppModule" templateFileName="ADF.Model.AppModule.vm" 
			subdir="" outputsubdir="" technicalPackage="view"
			file-extension="xml" file-prefix="" file-suffix="AppModule" 
			has-updatable-nature="true"
			scope-specific-value="model"
			>			
		</template>	
		
		<template name="ADF.Model.Entity" templateFileName="ADF.Model.Entity.vm" 
			subdir="" outputsubdir="" technicalPackage="view"
			file-extension="xml" file-prefix="" file-suffix="" 
			has-updatable-nature="true" add-package-name-dir="false"
			scope-specific-value="entity" 
			add-business-package-dir-name="false"
			>			
		</template>	
		
		<template name="ADF.Model.View" templateFileName="ADF.Model.View.vm" 
			subdir="" outputsubdir="" technicalPackage="view"
			file-extension="xml" file-prefix="" file-suffix="View" 
			has-updatable-nature="true"
			scope-specific-value="entity"
			add-business-package-dir-name="false"
			>			
		</template>	
		
		<template name="ADF.Model.FkAssoc" templateFileName="ADF.Model.FkAssoc.vm" 
			subdir="" outputsubdir="" technicalPackage="view"
			file-extension="xml" file-prefix="" file-suffix="FkAssoc" 
			has-updatable-nature="true"
			scope-specific-value="reference"
			add-business-package-dir-name="false"
			>			
		</template>	
		
		<template name="ADF.Model.FkLink" templateFileName="ADF.Model.FkLink.vm" 
			subdir="" outputsubdir="" technicalPackage="view"
			file-extension="xml" file-prefix="" file-suffix="FkLink" 
			has-updatable-nature="true"
			scope-specific-value="reference"
			add-business-package-dir-name="false"
			>			
		</template>	
		
		<template name="ADF.Model.ViewController" templateFileName="ADF.Model.ViewController.vm" 
			subdir="" outputsubdir="" technicalPackage="view"
			file-extension="jpx" file-prefix="" file-suffix="ViewController" 
			has-updatable-nature="true"
			scope-specific-value="model"
			>			
		</template>	
		
		<!-- SDO for entities -->
		
		<template name="ADF.SDO.AppModuleServiceImplJava" templateFileName="ADF.SDO.AppModuleServiceImplJava.vm" 
			subdir="" outputsubdir="" technicalPackage="view.server.serviceinterface"
			file-extension="java" file-prefix="" file-suffix="AppModuleServiceImpl" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="model"
			>			
		</template>			
		
		<template name="ADF.SDO.AppModuleServiceJava" templateFileName="ADF.SDO.AppModuleServiceJava.vm" 
			subdir="" outputsubdir="" technicalPackage="view.common.serviceinterface"
			file-extension="java" file-prefix="" file-suffix="AppModuleService" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="model"
			>			
		</template>	
		
		<template name="ADF.SDO.AppModuleServiceWsdl" templateFileName="ADF.SDO.AppModuleServiceWsdl.vm" 
			subdir="" outputsubdir="" technicalPackage="view.common.serviceinterface"
			file-extension="wsdl" file-prefix="" file-suffix="AppModuleService" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="model"
			>			
		</template>	
		
		<template name="ADF.SDO.AppModuleServiceXsd" templateFileName="ADF.SDO.AppModuleServiceXsd.vm" 
			subdir="" outputsubdir="" technicalPackage="view.common.serviceinterface"
			file-extension="xsd" file-prefix="" file-suffix="AppModuleService" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="model"
			>			
		</template>	
	    
	    <!-- package -->	
		<template name="ADF.SDO.ejb-jar" templateFileName="ADF.SDO.ejb-jar.vm" 
			subdir="" outputsubdir="META-INF" technicalPackage=""
			file-extension="xml" file-prefix="" file-suffix="ejb-jar" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="application"
			>
		</template>	
		
		<template name="ADF.SDO.weblogic-ejb-jar" templateFileName="ADF.SDO.weblogic-ejb-jar.vm" 
			subdir="" outputsubdir="META-INF" technicalPackage=""
			file-extension="xml" file-prefix="" file-suffix="weblogic-ejb-jar" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="application"
			>			
		</template>	
		
		<!-- SDO for entities -->

		<template name="ADF.SDO.EntityXsd" templateFileName="ADF.SDO.EntityXsd.vm" 
			subdir="" outputsubdir="" technicalPackage="view.common"
			file-extension="xsd" file-prefix="" file-suffix="" 
			has-updatable-nature="true" add-package-name-dir="false"
			scope-specific-value="entity"
			add-business-package-dir-name="false"
			>			
		</template>	
		
		<template name="ADF.SDO.ViewFace" templateFileName="ADF.SDO.ViewFace.vm" 
			subdir="" outputsubdir="" technicalPackage="view.common"
			file-extension="java" file-prefix="" file-suffix="ViewSDO" 
			has-updatable-nature="true"
			scope-specific-value="entity"
			add-business-package-dir-name="false"
			>			
		</template>	
		
		<template name="ADF.SDO.ViewImpl" templateFileName="ADF.SDO.ViewImpl.vm" 
			subdir="" outputsubdir="" technicalPackage="view.common"
			file-extension="java" file-prefix="" file-suffix="ViewSDOImpl" 
			has-updatable-nature="true"
			scope-specific-value="entity"
			add-business-package-dir-name="false"
			>			
		</template>	
		
    </template-target>

	<!-- ADF project specific -->
	<template-target 
    	name="ADF Model project"
		libdir="lib/ADF_LIB.vm"
		package-root=""
		outputdir="Model">
		
		<template name="ADF.Model.jpr" templateFileName="ADF.Model.jpr.vm" 
			subdir="" outputsubdir="" technicalPackage=""
			file-extension="jpr" file-prefix="" file-suffix="Model" 
			has-updatable-nature="true" add-model-name="false" add-package-name-dir="false"
			scope-specific-value="application"
			>			
		</template>			
		
	</template-target>
	
	<template-target 
    	name="ADF View Controller project"
		libdir="lib/ADF_LIB.vm"
		outputdir="ViewController">
		
	</template-target>
	
	<template-target 
    	name="ADF View Controller src"
		libdir="lib/ADF_LIB.vm"
		outputdir="ViewController/src">
		
	</template-target>
	
	<template-target 
    	name="ADF workspace"
		libdir="lib/ADF_LIB.vm"
		package-root=""
		outputdir="">
		
		<template name="ADF.jws" templateFileName="ADF.jws.vm" 
			subdir="" outputsubdir="" technicalPackage=""
			file-extension="jws" file-prefix="" file-suffix="Workspace" 
			has-updatable-nature="true" add-model-name="false"
			scope-specific-value="application"
			>			
		</template>				
	</template-target>
	
</target>
